import './language/compiling/compiler.test.js'
import './language/compiling/parsing.test.js'
import './language/compiling/semantics.test.js'
import './language/runtime/evaluator.test.js'
import './language/semantics/type-system.test.js'
